[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-f]{40}$')][string]$SourceCommit,
    [Parameter(Mandatory=$true)][string]$TargetBuildRoot,
    [Parameter(Mandatory=$true)][string]$BootstrapRecord,
    [Parameter(Mandatory=$true)][string]$UpgradePublicCertificate,
    [Parameter(Mandatory=$true)][string]$PreflightHostState,
    [Parameter(Mandatory=$true)][string]$OutputRoot,
    [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-f]{64}$')][string]$ExpectedScriptSha256
)

$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$packageRoot=[IO.Path]::GetFullPath($PSScriptRoot)
$repositoryRoot=[IO.Path]::GetFullPath((Join-Path $packageRoot '..\..\..'))
$target=[IO.Path]::GetFullPath($TargetBuildRoot)
$output=[IO.Path]::GetFullPath($OutputRoot)
$unit1Commit='d22610e96496f7a9209edff36442be843f06fed4'
$unit1Tree='8a627b54537e4c26835345907fc5181205ce496f'
$transitionNonce='bc3a3218-5f52-4f2c-9d5e-eceda24dab36'
$provisioningNonce='438bd38a-b02a-423f-bc5f-11847a8a76d9'
$expiration='2026-08-24T00:00:00.0000000Z'
$terminalLedgerId='899e4db2b5c0f4ad58a09c682324a2ee9e5d7e2f180822ce9300922e56741d52'
$terminalSid='S-1-5-80-1950096479-1020125124-2173088643-1633316353-879035948'
$upgradeSid='S-1-5-80-238545627-4117296865-2677355104-248304369-1301198082'

function Hash([string]$p){(Get-FileHash -LiteralPath ([IO.Path]::GetFullPath($p)) -Algorithm SHA256).Hash.ToLowerInvariant()}
function BytesHash([byte[]]$b){$a=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($a.ComputeHash($b))).Replace('-','').ToLowerInvariant()}finally{$a.Dispose()}}
function TextHash([string]$s){BytesHash ([Text.UTF8Encoding]::new($false).GetBytes($s))}
function ReadJson([string]$p){Get-Content -LiteralPath $p -Raw|ConvertFrom-Json}
function WriteRaw([object]$v,[string]$p){[IO.File]::WriteAllText($p,($v|ConvertTo-Json -Depth 100),[Text.UTF8Encoding]::new($false))}
function Canonical([object]$v,[string]$p,[string]$tool){$raw=$p+'.raw';if(Test-Path $p){throw "Output exists: $p"};WriteRaw $v $raw;& $tool canonicalize $raw $p|Out-Null;if($LASTEXITCODE -ne 0){throw "Canonicalization failed: $p"}}
function NewDir([string]$p){if(Test-Path $p){if(@(Get-ChildItem -LiteralPath $p -Force).Count){throw "Output root not empty: $p"}}else{New-Item -ItemType Directory -Path $p|Out-Null}}
function NormalizeIl([string]$binary,[string]$dest,[string]$ildasm){$raw=$dest+'.raw.il';& $ildasm /text /nobar /utf8 ("/out=$raw") $binary|Out-Null;if($LASTEXITCODE -ne 0){throw "ILDASM failed: $binary"};$t=[IO.File]::ReadAllText($raw);$m=[regex]::Match($t,'(?m)^// MVID: \{([0-9A-Fa-f-]+)\}\r?$');if(-not $m.Success){throw 'MVID absent'};$t=$t.Replace($m.Groups[1].Value,'NORMALIZED-MVID');$t=[regex]::Replace($t,'(?m)^// Image base: 0x[0-9A-Fa-f]+\r?$','// Image base: NORMALIZED');$t=[regex]::Replace($t,'(?m)^// WARNING: Created Win32 resource file .+\.raw\.res\r?$','// WARNING: Created Win32 resource file NORMALIZED.raw.res');[IO.File]::WriteAllText($dest,$t,[Text.UTF8Encoding]::new($false));Hash $dest}
function Compile([string]$main,[string]$define,[string]$dest,[string]$unit2Source,[string]$csc,[string[]]$refs,[string[]]$baseSources,[string]$devIdentity){$a=@('/nologo','/noconfig','/target:exe','/platform:x64','/optimize+','/checked+','/debug-','/warn:4','/warnaserror+','/nostdlib+','/langversion:5','/filealign:512',('/main:'+$main),('/out:'+$dest));if($define){$a+=('/define:'+$define)};foreach($r in $refs){$a+=('/reference:'+$r)};$a+=$baseSources;$a+=$unit2Source;$a+=$devIdentity;& $csc @a;if($LASTEXITCODE -ne 0){throw "Compilation failed: $main"}}

if((Hash $PSCommandPath) -cne $ExpectedScriptSha256){throw 'Build script identity mismatch'}
NewDir $output
foreach($d in @('Generated','PassA','PassB','NormalizedIL','Install','TargetStaging')){New-Item -ItemType Directory -Path (Join-Path $output $d)|Out-Null}
$registry=ReadJson (Join-Path $packageRoot 'external_utility_registry.json')
function Utility([string]$role){$r=@($registry.utilities|Where-Object{$_.role -ceq $role});if($r.Count -ne 1){throw "Utility role invalid: $role"};if((Hash ([string]$r[0].path)) -cne [string]$r[0].measurement.sha256){throw "Utility drift: $role"};$r[0]}
$gitRow=Utility 'GIT_BUILD_AND_VERIFICATION';$cscRow=Utility 'CSC_COMPILER';$ildasmRow=Utility 'ILDASM_TOOL'
$git=[string]$gitRow.path;$csc=[string]$cscRow.path;$ildasm=[string]$ildasmRow.path
$refs=@('COMPILER_REFERENCE_mscorlib.dll','COMPILER_REFERENCE_System.dll','COMPILER_REFERENCE_System.Core.dll','COMPILER_REFERENCE_System.Security.dll','COMPILER_REFERENCE_System.ServiceProcess.dll')|ForEach-Object{[string](Utility $_).path}
$head=(& $git --no-pager -c "safe.directory=$($repositoryRoot.Replace('\','/'))" -C $repositoryRoot rev-parse HEAD).Trim();if($LASTEXITCODE -ne 0 -or $head -cne $SourceCommit){throw 'Source HEAD mismatch'}
$status=@(& $git --no-pager -c "safe.directory=$($repositoryRoot.Replace('\','/'))" -C $repositoryRoot status --porcelain=v1 --untracked-files=all);if($status.Count){throw 'Source checkout not clean'}
$tree=(& $git --no-pager -c "safe.directory=$($repositoryRoot.Replace('\','/'))" -C $repositoryRoot show -s --format=%T $SourceCommit).Trim()
if($SourceCommit -ceq $unit1Commit){throw 'Unit 2 provisioning source must be committed after Unit 1'}
$bootstrap=ReadJson $BootstrapRecord
if([string]$bootstrap.source_commit -cne $SourceCommit -or [string]$bootstrap.source_tree -cne $tree -or [string]$bootstrap.service_sid -cne $upgradeSid -or [string]$bootstrap.prior_failed_attempt_status -cne 'PRESERVED_NONAUTHORITY_FAILURE' -or [string]$bootstrap.prior_failed_attempt_sha256 -notmatch '^[0-9a-f]{64}$' -or [string]$bootstrap.second_failed_attempt_status -cne 'PRESERVED_NONAUTHORITY_FAILURE' -or [string]$bootstrap.second_failed_attempt_sha256 -notmatch '^[0-9a-f]{64}$' -or [string]$bootstrap.third_failed_attempt_status -cne 'PRESERVED_NONAUTHORITY_FAILURE' -or [string]$bootstrap.third_failed_attempt_sha256 -notmatch '^[0-9a-f]{64}$' -or [string]$bootstrap.fourth_failed_attempt_status -cne 'PRESERVED_NONAUTHORITY_FAILURE' -or [string]$bootstrap.fourth_failed_attempt_sha256 -notmatch '^[0-9a-f]{64}$' -or $bootstrap.recovered_acl_mutation_in_current_attempt -ne $false -or (Hash $UpgradePublicCertificate) -cne [string]$bootstrap.public_certificate_sha256 -or [string]$bootstrap.public_export_sha256 -cne [string]$bootstrap.public_certificate_sha256){throw 'Bootstrap binding invalid'}
$preflightPath=[IO.Path]::GetFullPath($PreflightHostState);$preflight=ReadJson $preflightPath;$preflightSha=Hash $preflightPath
if([string]$preflight.artifact_type -cne 'R7_REMEDIATION_HOST_STATE_CAPTURE' -or [string]$preflight.phase -cne 'PRECHANGE' -or [int64]$preflight.ledger_entry_file_count -ne 678 -or [string]$preflight.checkpoint.raw_sha256 -cne '988f08177b04125e3f92f0696adac8c22b7d24ab0a4cba726145d97ea2958962'){throw 'Preflight host-state binding invalid'}
$terminalRow=@($preflight.terminal_authority_services|Where-Object{$_.name -ceq 'RandleTerminalAuthority'});if($terminalRow.Count -ne 1 -or [string]$terminalRow[0].state -cne 'Running' -or [string]$terminalRow[0].account -cne 'NT SERVICE\RandleTerminalAuthority' -or [string]$terminalRow[0].binary_sha256 -cne '9ea829416f37c94db2858586fa5e0042652f6caa4637a29fdbefb513577a7526'){throw 'Preflight terminal service binding invalid'}
foreach($fixed in @([ordered]@{path='C:\Program Files\RandleAI\TerminalAuthority\RandleTerminalAuthority.exe';sha='9ea829416f37c94db2858586fa5e0042652f6caa4637a29fdbefb513577a7526'},[ordered]@{path='C:\ProgramData\RandleAI\TerminalAuthority\Config\r7_terminal_authority_policy.json';sha='76eb2900b2000aa0b41e6040335cc323f7443728aad21cd871d5b6b8e17bcd8b'},[ordered]@{path='C:\ProgramData\RandleAI\TerminalAuthority\Ledger\checkpoint.json';sha='988f08177b04125e3f92f0696adac8c22b7d24ab0a4cba726145d97ea2958962'},[ordered]@{path='C:\ProgramData\RandleAI\TerminalAuthority\Trust\terminal_authority_public.cer';sha='b84a4de14577580c64ff5b2446f120aa6f9ea60faa2cb5465b495282f0273285'})){if((Hash ([string]$fixed.path)) -cne [string]$fixed.sha){throw "Current terminal state drift: $($fixed.path)"}}
$artifact=Join-Path $target 'Bootstrap\R7ArtifactTool.bootstrap.exe';if(-not(Test-Path $artifact)){throw 'Target artifact tool missing'}
$targetSummary=ReadJson (Join-Path $target 'build_summary.json');if([string]$targetSummary.source_commit -cne $unit1Commit -or [string]$targetSummary.source_tree -cne $unit1Tree){throw 'Target build source mismatch'}
$targetReceipt=Join-Path $target 'Generated\build_receipt.json';$targetReceiptSha=Hash $targetReceipt
$targetTemplate=ReadJson (Join-Path $target 'Generated\transition_request_template.json')
$dependency=Join-Path $target 'Generated\dependency_manifest.json';$dependencySha=Hash $dependency
$targetPolicy=Join-Path $target 'Generated\terminal_authority_v4_policy.json';$targetPolicySha=Hash $targetPolicy
$targetManifest=Join-Path $target 'Generated\authority_package_manifest.json';$targetManifestSha=Hash $targetManifest
if([string]$targetTemplate.build_receipt_sha256 -cne $targetReceiptSha -or [string]$targetTemplate.dependency_manifest_sha256 -cne $dependencySha){throw 'Target template binding invalid'}
$components=[Collections.Generic.List[object]]::new();$componentPaths=[Collections.Generic.HashSet[string]]::new([StringComparer]::Ordinal)
foreach($component in @($targetTemplate.components)){$components.Add([ordered]@{final_path=[string]$component.final_path;role=[string]$component.role;sha256=[string]$component.sha256;staging_relative_path=[string]$component.staging_relative_path});[void]$componentPaths.Add([string]$component.staging_relative_path)}
$targetManifestValue=ReadJson $targetManifest;$extraIndex=0
foreach($file in @($targetManifestValue.files|Sort-Object staging_relative_path)){if($componentPaths.Contains([string]$file.staging_relative_path)){continue};$components.Add([ordered]@{final_path=[string]$file.final_path;role=('PACKAGE_FILE_'+$extraIndex.ToString('D4')+'_'+([string]$file.raw_sha256).Substring(0,16));sha256=[string]$file.raw_sha256;staging_relative_path=[string]$file.staging_relative_path});[void]$componentPaths.Add([string]$file.staging_relative_path);$extraIndex++}

$keyPath=Join-Path 'C:\ProgramData\Microsoft\Crypto\Keys' ([string]$bootstrap.key_unique_name)
$keyMetadataPath=Join-Path $output 'Generated\upgrade_key_metadata.json';& $artifact measure-metadata $keyPath $keyMetadataPath|Out-Null;if($LASTEXITCODE -ne 0){throw 'Key metadata failed'};$key=ReadJson $keyMetadataPath
if([string]$key.owner_sid -cne 'S-1-5-18' -or [long]$key.hard_link_count -ne 1 -or [string]$key.security_descriptor_sha256 -cne [string]$bootstrap.key_file_acl_sha256){throw 'Key metadata mismatch'}
$volume=[string]$key.volume_identity;$certSha=Hash $UpgradePublicCertificate

$originalUnit2=Join-Path $packageRoot 'Source\R7Unit2UpgradeAuthority.cs';$text=[IO.File]::ReadAllText($originalUnit2,[Text.Encoding]::UTF8)
function BoundSource([hashtable]$replacements,[string]$path){$value=$text;foreach($k in $replacements.Keys){if(-not $value.Contains($k)){throw "Identity placeholder absent: $k"};$value=$value.Replace($k,[string]$replacements[$k])};[IO.File]::WriteAllText($path,$value,[Text.UTF8Encoding]::new($false))}
$clientSource=Join-Path $output 'Generated\R7Unit2ClientShared.g.cs';BoundSource @{'UNIT2_GENERATED_CERTIFICATE_SHA256'=$certSha} $clientSource
$baseSources=@(Get-ChildItem -LiteralPath (Join-Path $packageRoot 'Source') -Filter '*.cs' -File|Where-Object{$_.Name -ne 'R7Unit2UpgradeAuthority.cs'}|ForEach-Object FullName)
$devIdentity=Join-Path $packageRoot 'BuildInputs\R7DevelopmentIdentity.g.cs'
$roles=@(
    [ordered]@{role='UPGRADE_CLIENT';name='RandleTerminalUpgradeClient.exe';main='RandleAI.R7Remediation.R7Unit2UpgradeClientProgram'},
    [ordered]@{role='UPGRADE_PUBLIC_VERIFIER';name='RandleTerminalUpgradePublicVerifier.exe';main='RandleAI.R7Remediation.R7Unit2UpgradePublicVerifierProgram'},
    [ordered]@{role='UPGRADE_PROTOCOL_PROBE';name='RandleTerminalUpgradeProtocolProbe.exe';main='RandleAI.R7Remediation.R7Unit2UpgradeProbeProgram'}
)
$binary=@{}
foreach($r in $roles){$a=Join-Path $output ('PassA\'+$r.name);$b=Join-Path $output ('PassB\'+$r.name);Compile $r.main '' $a $clientSource $csc $refs $baseSources $devIdentity;Compile $r.main '' $b $clientSource $csc $refs $baseSources $devIdentity;$ia=NormalizeIl $a (Join-Path $output ('NormalizedIL\'+$r.name+'.a.il')) $ildasm;$ib=NormalizeIl $b (Join-Path $output ('NormalizedIL\'+$r.name+'.b.il')) $ildasm;if($ia -cne $ib){throw "Normalized IL mismatch: $($r.role)"};$binary[$r.role]=[ordered]@{normalized_il_sha256=$ia;raw_sha256=(Hash $a);role=$r.role;size=(Get-Item $a).Length}}

$requirementSha=Hash (Join-Path $packageRoot 'governed_requirement_registry.json');$caseSha=Hash (Join-Path $packageRoot 'immutable_case_definitions.json');$expectationSha=Hash (Join-Path $packageRoot 'immutable_expectations.json');$principalSha=Hash (Join-Path $packageRoot 'service_principal_registry.json');$scriptSha=Hash (Join-Path $packageRoot 'governed_script_registry.json');$utilitySha=Hash (Join-Path $packageRoot 'external_utility_registry.json')
$scopePath=Join-Path $packageRoot 'unit2_authorization_scope.json';$scopeSha=Hash $scopePath
$hostCore=[ordered]@{terminal_ledger_id=$terminalLedgerId;terminal_public_trust_sha256='b84a4de14577580c64ff5b2446f120aa6f9ea60faa2cb5465b495282f0273285';terminal_service_sid=$terminalSid;volume_identity=$volume}
$hostCorePath=Join-Path $output 'Generated\host_identity_input.json';Canonical $hostCore $hostCorePath $artifact;$hostIdentity=Hash $hostCorePath
$targetBindings=[ordered]@{authority_package_manifest_sha256=$targetManifestSha;build_receipt_sha256=$targetReceiptSha;case_definitions_sha256=$caseSha;dependency_manifest_sha256=$dependencySha;expectations_sha256=$expectationSha;expected_terminal_ledger_continuity='PRESERVE_SEQUENCE_678_ROOT_AND_CHECKPOINT_UNTIL_SEPARATE_INSTALL_UNIT';expected_terminal_public_trust_sha256='b84a4de14577580c64ff5b2446f120aa6f9ea60faa2cb5465b495282f0273285';interface_version='4.0.0-REMEDIATION';principal_registry_sha256=$principalSha;requirement_registry_sha256=$requirementSha;script_registry_sha256=$scriptSha;terminal_policy_sha256=$targetPolicySha;utility_registry_sha256=$utilitySha}
$authorityBindings=[ordered]@{fourth_failed_bootstrap_attempt_sha256=[string]$bootstrap.fourth_failed_attempt_sha256;independent_rejection_commit='9d813a4bad29ec04f022f54ffcae73a5d542eb44';preflight_baseline_sha256=$preflightSha;prior_failed_bootstrap_attempt_sha256=[string]$bootstrap.prior_failed_attempt_sha256;second_failed_bootstrap_attempt_sha256=[string]$bootstrap.second_failed_attempt_sha256;third_failed_bootstrap_attempt_sha256=[string]$bootstrap.third_failed_attempt_sha256;prohibited_source_commit='f0cfbce97e913a133530dd66a70326b1e03a0fb6';prohibited_source_dependency_count=0;provisioned_infrastructure_commit='bb04ac54fb328516d0c785f4e6551e6a20d73759';provisioning_commit=$SourceCommit;r6_commit='87d066eb16d7fe0b6a1677ea7739c5c2ead4ad94';r7_record_commits=@('06c6805ed52a0d539a73088c097c60dec335462a','8ec5697b3c6fd9d93b972113b7e79d033b4cb1f6');unit1_commit=$unit1Commit;unit2_authorization_scope_sha256=$scopeSha}
$rollback=[ordered]@{automatic_rollback=$false;existing_terminal_ledger_rewrite='PROHIBITED';governed_rollback_authorization_required=$true;rejected_v3_reinstall='PROHIBITED';v1_rollback='PROHIBITED'}
$threat=[ordered]@{excludes=@('kernel','offline_administrator','physical_attack','TPM_or_HSM_claim');protects=@('terminal_self_authorization','caller_selected_components','component_substitution','cross_host_replay','policy_downgrade','interface_downgrade','authorization_replay')}
$plan=[ordered]@{components=$components.ToArray();current_checkpoint_sha256='988f08177b04125e3f92f0696adac8c22b7d24ab0a4cba726145d97ea2958962';current_ledger_root='87fdc1bbcef606ad134cf5cd2c0cad83dd4df25ed96544c05fd5adbeff5f82e5';current_ledger_sequence=678;host_identity=$hostIdentity;target_bindings=$targetBindings;transition_nonce=$transitionNonce}
$planPath=Join-Path $output 'Generated\transition_plan.json';Canonical $plan $planPath $artifact;$planSha=Hash $planPath
$ledgerId=TextHash ('R7_UNIT2_UPGRADE_LEDGER|'+$certSha+'|'+$terminalLedgerId+'|'+$SourceCommit)
$hardener=Join-Path $packageRoot 'complete_unit2_upgrade_authority.ps1';if(-not(Test-Path $hardener)){throw 'Unit 2 completion script absent'}
$policy=[ordered]@{
 artifact_type='R7_UNIT2_SEPARATE_UPGRADE_AUTHORITY_POLICY';authority_bindings=$authorityBindings;authorization_expiration=$expiration;authorization_scope_sha256=$scopeSha;bootstrap_authority='EXPLICIT_R7_REMEDIATION_UNIT_2_AUTHORIZATION';dependency_manifest_sha256=$dependencySha;
 fixed_roots=@('C:\Program Files\RandleAI\TerminalUpgradeAuthority','C:\ProgramData\RandleAI\TerminalUpgradeAuthority\Config','C:\ProgramData\RandleAI\TerminalUpgradeAuthority\Ledger','C:\ProgramData\RandleAI\TerminalUpgradeAuthority\Trust','C:\ProgramData\RandleAI\TerminalUpgradeAuthority\Evidence','C:\ProgramData\RandleAI\TerminalUpgradeAuthority\Responses','C:\ProgramData\RandleAI\TerminalUpgradeAuthority\Objects','C:\ProgramData\RandleAI\TerminalUpgradeAuthority\Authorizations','C:\ProgramData\RandleAI\TerminalUpgradeAuthority\Recovery','C:\ProgramData\RandleAI\TerminalUpgradeAuthority\Staging');
 host_binding=[ordered]@{checkpoint_sha256='988f08177b04125e3f92f0696adac8c22b7d24ab0a4cba726145d97ea2958962';host_identity=$hostIdentity;terminal_interface='3.0.0-DRAFT';terminal_ledger_id=$terminalLedgerId;terminal_ledger_root='87fdc1bbcef606ad134cf5cd2c0cad83dd4df25ed96544c05fd5adbeff5f82e5';terminal_ledger_sequence=678;terminal_policy_sha256='76eb2900b2000aa0b41e6040335cc323f7443728aad21cd871d5b6b8e17bcd8b';terminal_public_trust_sha256='b84a4de14577580c64ff5b2446f120aa6f9ea60faa2cb5465b495282f0273285';terminal_service_binary_sha256='9ea829416f37c94db2858586fa5e0042652f6caa4637a29fdbefb513577a7526';terminal_service_name='RandleTerminalAuthority';terminal_service_sid=$terminalSid;volume_identity=$volume};
 installer_script_sha256=[string]$targetTemplate.installer_identity.script_sha256;interface_version='1.0.0';key=[ordered]@{algorithm='RSA-3072';export_policy='NONEXPORTABLE';key_unique_name=[string]$bootstrap.key_unique_name;provider='Microsoft Software Key Storage Provider';scope='LocalMachine';signature_algorithm='RSA-PSS-SHA256'};ledger_id=$ledgerId;minimum_terminal_version='4.0.0-REMEDIATION';operation_allowlist=@('AUTHORIZE_TERMINAL_TRANSITION','GET_AUTHORIZATION','GET_HEALTH','GET_PUBLIC_IDENTITY');preflight_baseline_sha256=$preflightSha;protocol_version='4.0';provisioning_nonce=$provisioningNonce;provisioning_script_sha256=(Hash $hardener);public_certificate_sha256=$certSha;required_components=$components.ToArray();revoked_component_sha256=@('632afaeeaf15c26ac057b34692ac672e03bc02f60fbb35177c378736b5e316ba','9ea829416f37c94db2858586fa5e0042652f6caa4637a29fdbefb513577a7526','76eb2900b2000aa0b41e6040335cc323f7443728aad21cd871d5b6b8e17bcd8b');rollback_constraints=$rollback;schema_version='2.0.0';service=[ordered]@{account='NT SERVICE\RandleTerminalUpgradeAuthority';denied_logon_rights=@('SeDenyInteractiveLogonRight','SeDenyRemoteInteractiveLogonRight');name='RandleTerminalUpgradeAuthority';pipe='RandleAI.TerminalUpgradeAuthority.v1';required_privileges=@('SeChangeNotifyPrivilege');sid=$upgradeSid;sid_type='RESTRICTED'};source_bindings=[ordered]@{provisioning_commit=$SourceCommit;provisioning_tree=$tree;target_commit=$unit1Commit;target_tree=$unit1Tree;unit1_commit=$unit1Commit;unit1_tree=$unit1Tree};target_bindings=$targetBindings;threat_model=$threat;transition_nonce=$transitionNonce;transition_plan_sha256=$planSha;upgrade_client_sha256=[string]$binary.UPGRADE_CLIENT.raw_sha256;upgrade_probe_sha256=[string]$binary.UPGRADE_PROTOCOL_PROBE.raw_sha256;upgrade_public_verifier_sha256=[string]$binary.UPGRADE_PUBLIC_VERIFIER.raw_sha256;volume_identity=$volume
}
$policyPath=Join-Path $output 'Generated\unit2_upgrade_policy.json';Canonical $policy $policyPath $artifact;$policySha=Hash $policyPath
$serviceSource=Join-Path $output 'Generated\R7Unit2Service.g.cs';BoundSource @{'UNIT2_GENERATED_CERTIFICATE_SHA256'=$certSha;'UNIT2_GENERATED_POLICY_SHA256'=$policySha;'UNIT2_GENERATED_DEPENDENCY_SHA256'=$dependencySha;'UNIT2_GENERATED_SOURCE_COMMIT'=$SourceCommit;'UNIT2_GENERATED_SOURCE_TREE'=$tree;'UNIT2_GENERATED_KEY_FILE_PATH'=$keyPath;'UNIT2_GENERATED_KEY_OWNER_SID'=[string]$key.owner_sid;'UNIT2_GENERATED_KEY_ACL_SHA256'=[string]$key.security_descriptor_sha256;'UNIT2_GENERATED_KEY_VOLUME_IDENTITY'=[string]$key.volume_identity;'UNIT2_GENERATED_KEY_FILE_IDENTITY'=[string]$key.file_identity} $serviceSource
$sa=Join-Path $output 'PassA\RandleTerminalUpgradeAuthority.exe';$sb=Join-Path $output 'PassB\RandleTerminalUpgradeAuthority.exe';Compile 'RandleAI.R7Remediation.R7Unit2UpgradeServiceProgram' 'UNIT2_SERVICE' $sa $serviceSource $csc $refs $baseSources $devIdentity;Compile 'RandleAI.R7Remediation.R7Unit2UpgradeServiceProgram' 'UNIT2_SERVICE' $sb $serviceSource $csc $refs $baseSources $devIdentity;$sia=NormalizeIl $sa (Join-Path $output 'NormalizedIL\RandleTerminalUpgradeAuthority.a.il') $ildasm;$sib=NormalizeIl $sb (Join-Path $output 'NormalizedIL\RandleTerminalUpgradeAuthority.b.il') $ildasm;if($sia -cne $sib){throw 'Service normalized IL mismatch'};$binary.UPGRADE_AUTHORITY=[ordered]@{normalized_il_sha256=$sia;raw_sha256=(Hash $sa);role='UPGRADE_AUTHORITY';size=(Get-Item $sa).Length}
$compilerOptions=@('/nologo','/noconfig','/target:exe','/platform:x64','/optimize+','/checked+','/debug-','/warn:4','/warnaserror+','/nostdlib+','/langversion:5','/filealign:512')
$scripts=@(Get-ChildItem -LiteralPath $packageRoot -Filter '*.ps1' -File|Sort-Object Name|ForEach-Object{[ordered]@{path=$_.Name;raw_sha256=(Hash $_.FullName);size=$_.Length}})
$sources=@(Get-ChildItem -LiteralPath (Join-Path $packageRoot 'Source') -Filter '*.cs' -File|Sort-Object Name|ForEach-Object{[ordered]@{path=('Source/'+$_.Name);raw_sha256=(Hash $_.FullName);size=$_.Length}})
$toolchain=@($cscRow,$ildasmRow,$gitRow)|ForEach-Object{[ordered]@{measurement=$_.measurement;role=$_.role}}
$receipt=[ordered]@{artifact_type='R7_UNIT2_UPGRADE_AUTHORITY_SOURCE_TO_BINARY_RECEIPT';binaries=@($binary.UPGRADE_AUTHORITY,$binary.UPGRADE_CLIENT,$binary.UPGRADE_PROTOCOL_PROBE,$binary.UPGRADE_PUBLIC_VERIFIER);compiler_options=$compilerOptions;dependency_manifest_sha256=$dependencySha;governed_scripts=$scripts;policy_sha256=$policySha;schema_version='1.0.0';source_commit=$SourceCommit;source_files=$sources;source_tree=$tree;target_build_receipt_sha256=$targetReceiptSha;target_source_commit=$unit1Commit;target_source_tree=$unit1Tree;toolchain=$toolchain}
$receiptPath=Join-Path $output 'Generated\unit2_build_receipt.json';Canonical $receipt $receiptPath $artifact
Copy-Item -LiteralPath $sa -Destination (Join-Path $output 'Install\RandleTerminalUpgradeAuthority.exe');Copy-Item -LiteralPath (Join-Path $output 'PassA\RandleTerminalUpgradeClient.exe') -Destination (Join-Path $output 'Install\RandleTerminalUpgradeClient.exe');Copy-Item -LiteralPath (Join-Path $output 'PassA\RandleTerminalUpgradeProtocolProbe.exe') -Destination (Join-Path $output 'Install\RandleTerminalUpgradeProtocolProbe.exe');Copy-Item -LiteralPath (Join-Path $output 'PassA\RandleTerminalUpgradePublicVerifier.exe') -Destination (Join-Path $output 'Install\RandleTerminalUpgradePublicVerifier.exe');Copy-Item -LiteralPath $policyPath -Destination (Join-Path $output 'Install\unit2_upgrade_policy.json');Copy-Item -LiteralPath $dependency -Destination (Join-Path $output 'Install\dependency_manifest.json');Copy-Item -LiteralPath $receiptPath -Destination (Join-Path $output 'Install\unit2_build_receipt.json');Copy-Item -LiteralPath $UpgradePublicCertificate -Destination (Join-Path $output 'Install\upgrade_authority_public.cer')
foreach($item in Get-ChildItem -LiteralPath (Join-Path $target 'Staging') -Force){Copy-Item -LiteralPath $item.FullName -Destination (Join-Path $output 'TargetStaging') -Recurse}
$manifestRows=@(Get-ChildItem -LiteralPath $output -File -Recurse|Where-Object{$_.FullName -notlike '*.raw' -and $_.FullName -notlike '*.raw.il'}|Sort-Object FullName|ForEach-Object{[ordered]@{path=$_.FullName.Substring($output.Length+1).Replace('\','/');raw_sha256=(Hash $_.FullName);size=$_.Length}})
$manifest=[ordered]@{artifact_type='R7_UNIT2_BUILD_OUTPUT_MANIFEST';files=$manifestRows;policy_sha256=$policySha;schema_version='1.0.0';source_commit=$SourceCommit;source_tree=$tree;status='PASS';target_source_commit=$unit1Commit;transition_plan_sha256=$planSha}
$manifestPath=Join-Path $output 'unit2_build_manifest.json';Canonical $manifest $manifestPath $artifact
[ordered]@{build_manifest_sha256=(Hash $manifestPath);output_root=$output;policy_sha256=$policySha;service_sha256=[string]$binary.UPGRADE_AUTHORITY.raw_sha256;source_commit=$SourceCommit;source_tree=$tree;status='PASS';target_build_receipt_sha256=$targetReceiptSha;transition_plan_sha256=$planSha}|ConvertTo-Json
