[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-f]{40}$')][string]$SourceCommit,
    [Parameter(Mandatory=$true)][string]$BuildRoot,
    [Parameter(Mandatory=$true)][string]$BootstrapRecord,
    [Parameter(Mandatory=$true)][string]$PreflightHostState,
    [Parameter(Mandatory=$true)][string]$UtilityRegistry,
    [Parameter(Mandatory=$true)][string]$EvidenceRoot,
    [Parameter(Mandatory=$true)][ValidatePattern('^[0-9a-f]{64}$')][string]$ExpectedScriptSha256
)
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$service='RandleTerminalUpgradeAuthority';$account='NT SERVICE\RandleTerminalUpgradeAuthority';$terminal='NT SERVICE\RandleTerminalAuthority';$sid='S-1-5-80-238545627-4117296865-2677355104-248304369-1301198082';$nonce='bc3a3218-5f52-4f2c-9d5e-eceda24dab36'
$install='C:\Program Files\RandleAI\TerminalUpgradeAuthority';$state='C:\ProgramData\RandleAI\TerminalUpgradeAuthority';$build=[IO.Path]::GetFullPath($BuildRoot);$evidence=[IO.Path]::GetFullPath($EvidenceRoot)
function Hash([string]$p){(Get-FileHash -LiteralPath ([IO.Path]::GetFullPath($p)) -Algorithm SHA256).Hash.ToLowerInvariant()}
function Run([string]$exe,[string[]]$a){& $exe @a;if($LASTEXITCODE -ne 0){throw "$exe exited $LASTEXITCODE | $($a -join ' ')"}}
function CopyNew([string]$s,[string]$d){if(Test-Path -LiteralPath $d){throw "Install target exists: $d"};Copy-Item -LiteralPath $s -Destination $d}
if(-not([Security.Principal.WindowsPrincipal]::new([Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator))){throw 'Elevation required'}
if((Hash $PSCommandPath) -cne $ExpectedScriptSha256){throw 'Completion script identity mismatch'}
$utility=Get-Content -LiteralPath ([IO.Path]::GetFullPath($UtilityRegistry)) -Raw|ConvertFrom-Json
function Utility([string]$role){$rows=@($utility.utilities|Where-Object{$_.role -ceq $role});if($rows.Count -ne 1){throw "Utility role invalid: $role"};$path=[IO.Path]::GetFullPath([string]$rows[0].path);if((Hash $path) -cne [string]$rows[0].measurement.sha256){throw "Utility drift: $role"};return $rows[0]}
$scRow=Utility 'SC_SERVICE_CONTROL_TOOL';$icaclsRow=Utility 'ICACLS_ACL_TOOL';$powershellRow=Utility 'POWERSHELL_ORCHESTRATOR';$sc=[string]$scRow.path;$icacls=[string]$icaclsRow.path
$currentPowerShell=[Diagnostics.Process]::GetCurrentProcess().MainModule.FileName;if(-not([IO.Path]::GetFullPath($currentPowerShell).Equals([IO.Path]::GetFullPath([string]$powershellRow.path),[StringComparison]::OrdinalIgnoreCase)) -or (Hash $currentPowerShell) -cne [string]$powershellRow.measurement.sha256){throw 'PowerShell orchestrator identity mismatch'}
$preflightPath=[IO.Path]::GetFullPath($PreflightHostState);$preflight=Get-Content -LiteralPath $preflightPath -Raw|ConvertFrom-Json;$preflightSha=Hash $preflightPath;if([string]$preflight.artifact_type -cne 'R7_REMEDIATION_HOST_STATE_CAPTURE' -or [string]$preflight.phase -cne 'PRECHANGE' -or [int64]$preflight.ledger_entry_file_count -ne 678 -or [string]$preflight.checkpoint.raw_sha256 -cne '988f08177b04125e3f92f0696adac8c22b7d24ab0a4cba726145d97ea2958962'){throw 'Preflight host-state identity invalid'}
function TerminalSnapshot {
 $svc=Get-Service -Name 'RandleTerminalAuthority' -ErrorAction Stop;$cim=Get-CimInstance Win32_Service -Filter "Name='RandleTerminalAuthority'";$binary='C:\Program Files\RandleAI\TerminalAuthority\RandleTerminalAuthority.exe';$policy='C:\ProgramData\RandleAI\TerminalAuthority\Config\r7_terminal_authority_policy.json';$checkpoint='C:\ProgramData\RandleAI\TerminalAuthority\Ledger\checkpoint.json';$trust='C:\ProgramData\RandleAI\TerminalAuthority\Trust\terminal_authority_public.cer';$policyJson=Get-Content -LiteralPath $policy -Raw|ConvertFrom-Json;$entryCount=@(Get-ChildItem -LiteralPath 'C:\ProgramData\RandleAI\TerminalAuthority\Ledger' -Filter '*.entry.json' -File).Count
 return [ordered]@{account=[string]$cim.StartName;binary_path=[string]$cim.PathName;binary_sha256=(Hash $binary);checkpoint_sha256=(Hash $checkpoint);interface=[string]$policyJson.interface_version;ledger_entry_count=$entryCount;ledger_root='87fdc1bbcef606ad134cf5cd2c0cad83dd4df25ed96544c05fd5adbeff5f82e5';policy_sha256=(Hash $policy);process_id=[long]$cim.ProcessId;service_state=[string]$svc.Status;trust_sha256=(Hash $trust)}
}
function AssertTerminalSnapshot([object]$v){if([string]$v.account -cne 'NT SERVICE\RandleTerminalAuthority' -or [string]$v.binary_path -cne 'C:\Program Files\RandleAI\TerminalAuthority\RandleTerminalAuthority.exe' -or [string]$v.binary_sha256 -cne '9ea829416f37c94db2858586fa5e0042652f6caa4637a29fdbefb513577a7526' -or [string]$v.policy_sha256 -cne '76eb2900b2000aa0b41e6040335cc323f7443728aad21cd871d5b6b8e17bcd8b' -or [string]$v.interface -cne '3.0.0-DRAFT' -or [int64]$v.ledger_entry_count -ne 678 -or [string]$v.checkpoint_sha256 -cne '988f08177b04125e3f92f0696adac8c22b7d24ab0a4cba726145d97ea2958962' -or [string]$v.trust_sha256 -cne 'b84a4de14577580c64ff5b2446f120aa6f9ea60faa2cb5465b495282f0273285' -or [string]$v.service_state -cne 'Running'){throw 'Existing terminal baseline drift'}}
$manifest=Get-Content -LiteralPath (Join-Path $build 'unit2_build_manifest.json') -Raw|ConvertFrom-Json;if([string]$manifest.source_commit -cne $SourceCommit -or [string]$manifest.status -cne 'PASS'){throw 'Build manifest binding invalid'}
$bootstrap=Get-Content -LiteralPath $BootstrapRecord -Raw|ConvertFrom-Json;if([string]$bootstrap.service_sid -cne $sid){throw 'Bootstrap SID mismatch'}
$svc=Get-Service -Name $service -ErrorAction Stop;if($svc.Status -ne 'Stopped'){throw 'Upgrade service must be stopped before first install'}
$terminalBefore=TerminalSnapshot;AssertTerminalSnapshot $terminalBefore
if(-not(Test-Path $evidence)){New-Item -ItemType Directory -Path $evidence|Out-Null}
$roots=@($install,$state,(Join-Path $state 'Activations'),(Join-Path $state 'Authorizations'),(Join-Path $state 'Config'),(Join-Path $state 'Config\BuildInputClosures'),(Join-Path $state 'Config\SourceInputs'),(Join-Path $state 'Evidence'),(Join-Path $state 'Ledger'),(Join-Path $state 'Objects'),(Join-Path $state 'Recovery'),(Join-Path $state 'Responses'),(Join-Path $state 'Staging'),(Join-Path $state 'Trust'))
foreach($root in $roots){if(-not(Test-Path -LiteralPath $root)){New-Item -ItemType Directory -Path $root|Out-Null}}
foreach($root in @($install,$state)){Run $icacls @($root,'/setowner','SYSTEM','/T','/C');Run $icacls @($root,'/inheritance:r','/grant:r','SYSTEM:(OI)(CI)(F)','BUILTIN\Administrators:(OI)(CI)(F)',"$account`:(OI)(CI)(RX)","$terminal`:(OI)(CI)(RX)",'BUILTIN\Users:(OI)(CI)(RX)','/T','/C')}
$mutable=@('Activations','Authorizations','Evidence','Ledger','Objects','Recovery','Responses')|ForEach-Object{Join-Path $state $_}
foreach($root in $mutable){Run $icacls @($root,'/inheritance:r','/grant:r','SYSTEM:(OI)(CI)(F)','BUILTIN\Administrators:(OI)(CI)(F)',"$account`:(OI)(CI)(F)","$terminal`:(OI)(CI)(RX)",'BUILTIN\Users:(OI)(CI)(RX)','/T','/C')}
$stageRoot=Join-Path (Join-Path $state 'Staging') $nonce;if(Test-Path $stageRoot){throw 'Transition staging root already exists'};New-Item -ItemType Directory -Path $stageRoot|Out-Null
foreach($item in Get-ChildItem -LiteralPath (Join-Path $build 'TargetStaging') -Force){Copy-Item -LiteralPath $item.FullName -Destination $stageRoot -Recurse}
Run $icacls @($stageRoot,'/setowner','SYSTEM','/T','/C');Run $icacls @($stageRoot,'/inheritance:r','/grant:r','SYSTEM:(OI)(CI)(F)','BUILTIN\Administrators:(OI)(CI)(F)',"$account`:(OI)(CI)(RX)",'BUILTIN\Users:(OI)(CI)(RX)','/T','/C')
$installInput=Join-Path $build 'Install'
CopyNew (Join-Path $installInput 'RandleTerminalUpgradeAuthority.exe') (Join-Path $install 'RandleTerminalUpgradeAuthority.exe');CopyNew (Join-Path $installInput 'RandleTerminalUpgradeClient.exe') (Join-Path $install 'RandleTerminalUpgradeClient.exe');CopyNew (Join-Path $installInput 'RandleTerminalUpgradeProtocolProbe.exe') (Join-Path $install 'RandleTerminalUpgradeProtocolProbe.exe');CopyNew (Join-Path $installInput 'RandleTerminalUpgradePublicVerifier.exe') (Join-Path $install 'RandleTerminalUpgradePublicVerifier.exe')
CopyNew (Join-Path $installInput 'unit2_upgrade_policy.json') (Join-Path $state 'Config\upgrade_authority_policy.json');CopyNew (Join-Path $installInput 'dependency_manifest.json') (Join-Path $state 'Config\dependency_manifest.json');CopyNew (Join-Path $installInput 'unit2_build_receipt.json') (Join-Path $state 'Config\upgrade_authority_build_receipt.json')
$certTarget=Join-Path $state 'Trust\upgrade_authority_public.cer';if((Hash (Join-Path $installInput 'upgrade_authority_public.cer')) -cne (Hash $certTarget)){throw 'Public certificate differs from bootstrap'}
foreach($root in @($install,(Join-Path $state 'Config'),(Join-Path $state 'Trust'))){Run $icacls @($root,'/setowner','SYSTEM','/T','/C');Run $icacls @($root,'/inheritance:r','/grant:r','SYSTEM:(OI)(CI)(F)','BUILTIN\Administrators:(OI)(CI)(F)',"$account`:(OI)(CI)(RX)","$terminal`:(OI)(CI)(RX)",'BUILTIN\Users:(OI)(CI)(RX)','/T','/C')}
$boundaryPath=Join-Path $evidence 'prestart_service_boundary.json';& (Join-Path $install 'RandleTerminalUpgradePublicVerifier.exe') apply-boundary $boundaryPath;if($LASTEXITCODE -ne 0){throw 'Prestart service boundary enforcement failed'}
Run $sc @('start',$service)
$deadline=[DateTime]::UtcNow.AddSeconds(30);do{$svc=Get-Service -Name $service;if($svc.Status -eq 'Running'){break};Start-Sleep -Milliseconds 250}while([DateTime]::UtcNow -lt $deadline);if($svc.Status -ne 'Running'){throw 'Upgrade service failed to start'}
$terminalAfter=TerminalSnapshot;AssertTerminalSnapshot $terminalAfter;if([int64]$terminalBefore.process_id -ne [int64]$terminalAfter.process_id){throw 'Existing terminal service process changed'}
$installed=@(Get-ChildItem -LiteralPath $install -File|Sort-Object Name|ForEach-Object{[ordered]@{path=$_.FullName;raw_sha256=(Hash $_.FullName);size=$_.Length}})
$record=[ordered]@{artifact_type='R7_UNIT2_UPGRADE_AUTHORITY_COMPLETION_RECORD';build_manifest_sha256=(Hash (Join-Path $build 'unit2_build_manifest.json'));existing_terminal_after=$terminalAfter;existing_terminal_before=$terminalBefore;installed_files=$installed;preflight_baseline_sha256=$preflightSha;schema_version='1.0.0';service_name=$service;service_sid=$sid;source_commit=$SourceCommit;staging_root=$stageRoot;status='PASS';terminal_installation_performed=$false;utilities=@([ordered]@{role=[string]$scRow.role;sha256=[string]$scRow.measurement.sha256},[ordered]@{role=[string]$icaclsRow.role;sha256=[string]$icaclsRow.measurement.sha256},[ordered]@{role=[string]$powershellRow.role;sha256=[string]$powershellRow.measurement.sha256})}
$recordPath=Join-Path $evidence 'unit2_completion_record.json';[IO.File]::WriteAllText($recordPath,($record|ConvertTo-Json -Depth 20),[Text.UTF8Encoding]::new($false));Get-FileHash -LiteralPath $recordPath -Algorithm SHA256
