#!/usr/bin/env python3
"""Build a closed content manifest for the dedicated R7 Python runtime."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any


def canonical(value: Any) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8") + b"\n"


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--runtime-root", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    root = args.runtime_root.resolve(strict=True)
    files: list[dict[str, Any]] = []
    for path in sorted((item for item in root.rglob("*") if item.is_file()), key=lambda item: item.relative_to(root).as_posix()):
        relative = path.relative_to(root).as_posix()
        if "__pycache__" in path.parts or path.suffix.lower() in {".pyc", ".pyo"}:
            raise RuntimeError(f"generated bytecode is forbidden: {relative}")
        raw = path.read_bytes()
        files.append({"path": relative, "sha256": sha256(raw), "size": len(raw)})
    root_identity = sha256(canonical(files))
    manifest = {
        "artifact_type": "R7_DEDICATED_PYTHON_RUNTIME_MANIFEST",
        "file_count": len(files),
        "files": files,
        "installed_root": "C:/Program Files/RandleAI/TerminalAuthority/PythonRuntime",
        "python_executable_sha256": "624bbc0586d8855633b875e911883bbef8a0e8b8711e11126df480dd86f54181",
        "python_version": "3.12.2",
        "runtime_root_identity": root_identity,
        "schema_version": "7.1.0-DRAFT",
        "source_model": "MEASURED_CPYTHON_3_12_2_PLUS_EXACT_R7_LOCKED_DISTRIBUTION_FILES",
    }
    args.output.write_bytes(canonical(manifest))
    print(json.dumps({"file_count": len(files), "manifest_sha256": sha256(args.output.read_bytes()), "runtime_root_identity": root_identity}, sort_keys=True, separators=(",", ":")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
